dist: xenial
language: python
git:
  # chartpress may fail with shallow clones
  depth: false
services:
  - docker
install:
  - pip3 install --no-cache-dir -r dev-requirements.txt
  - . "ci/minikube-${SCENARIO}.env"
  - ./ci/install.sh
script:
  - ./ci/travis-script.sh

env:
  matrix:
    - SCENARIO=1.14-default
