# Default values for omero-web
replicaCount: 1

web:
  image:
    repository: openmicroscopy/omero-web
    tag: 5.4.5
    pullPolicy: IfNotPresent
  resources: {}
  prefix:
  serverList: '[["omero-server", 4064, "omero"]]'
  config:
    set: {}
    append: {}
  secure: true

nginx:
  image:
    repository: library/nginx
    tag: 1.13.7
    pullPolicy: IfNotPresent
  resources: {}
  generateConf: true

service:
  name: omero-web
  type: ClusterIP
  externalPort: 80

ingress:
  enabled: false
  hosts:
  annotations:
  tls:

redis:
  enabled: true
  # TODO: Use the augenerated redis secret instead
  redisPassword: ChAnGeMe
  persistence:
    # Session storage only
    enabled: false
