kind: ConfigMap
apiVersion: v1
metadata:
  name: omero-web-config
data:

  web.omero: |
    config set -- omero.web.secure true
    config set -- omero.web.server_list '{{ .Values.serverList | toJson }}'

    config set -- omero.web.prefix {{ .Values.prefix | trimSuffix "/" }}
    config set -- omero.web.static_url {{ .Values.prefix | trimSuffix "/" }}/static

    {{- if .Values.redis.enabled }}
    config set -- omero.web.session_engine django.contrib.sessions.backends.cache
    config set -- omero.web.caches '{ "default": { "BACKEND": "django_redis.cache.RedisCache", "LOCATION": "redis://:{{ .Values.redis.redisPassword }}@{{ .Release.Name }}-redis:6379/0" } }'

    {{- end }}

    {{- range $key, $value := .Values.config.set }}
    config set -- {{ $key }} {{ $value }}
    {{- end }}

    {{- range $keyvalues := .Values.config.append }}
    {{- range $key, $value := $keyvalues }}
    config append -- {{ $key }} {{ $value }}
    {{- end }}
    {{- end }}

    {{- range $keyvalues := .Values.config.appendJson }}
    {{- range $key, $value := $keyvalues }}
    config append -- {{ $key }} '{{ $value | toJson }}'
    {{- end }}
    {{- end }}
