apiVersion: v1
kind: Service
metadata:
  name: {{ include "omero-web.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "omero-web.name" . }}
    helm.sh/chart: {{ include "omero-web.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  {{- if and (contains "LoadBalancer" .Values.service.type) .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end}}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "omero-web.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
