apiVersion: v1
kind: Service
metadata:
  name: {{ include "omero-server.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "omero-server.name" . }}
    helm.sh/chart: {{ include "omero-server.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  {{- if and (contains "LoadBalancer" .Values.service.type) .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end}}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: ice-srouter
      protocol: TCP
      name: ice-srouter
    {{- if and (contains "NodePort" .Values.service.type) .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
    {{- end}}
  selector:
    app.kubernetes.io/name: {{ include "omero-server.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
