---
name: Test and Publish

on:
  pull_request:
  push:

jobs:
  precommit:
    runs-on: ubuntu-latest
    name: Run pre-commit
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - uses: pre-commit/action@v3.0.0

  test_omero:
    runs-on: ubuntu-latest
    name: Test OMERO Helm charts
    strategy:
      matrix:
        include:
          - k3s-version: v1.21.0+k3s1
            helm-version: v3.5.4
          - k3s-version: v1.23.6+k3s1
            helm-version: v3.9.0
    steps:
      - uses: actions/checkout@v3
        with:
          # chartpress requires the full history
          fetch-depth: 0

      - id: k3s
        uses: jupyterhub/action-k3s-helm@v2.0.0
        with:
          k3s-version: ${{ matrix.k3s-version }}
          helm-version: ${{ matrix.helm-version }}
        # This action should export KUBECONFIG
      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - name: Install dependencies
        run: |
          conda install -y -q -c ome omero-py pytest requests ruamel.yaml docker-py
          # $CONDA/bin/pip install -r dev-requirements.txt
          echo "$CONDA/bin" >> $GITHUB_PATH
      - name: Build
        run: ./ci/build.sh
      - name: Test
        run: ./ci/test.sh

  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    name: Publish OMERO Helm charts
    if: github.ref == 'refs/heads/main'
    needs:
      - precommit
      - test_omero
    steps:
      - uses: actions/checkout@v3
        with:
          # chartpress requires the full history
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - uses: azure/setup-helm@v1
        with:
          version: v3.5.4
      - name: Install dependencies
        run: pip install -r dev-requirements.txt
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Publish
        run: ./ci/chartpress.py --git-release --tag-latest --push --publish-chart --git-push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Required for git commit:
          EMAIL: chartpress-bot@example.org
          GIT_AUTHOR_NAME: chartpress-bot
          GIT_COMMITTER_NAME: chartpress-bot
