---
name: Test

on:
  pull_request:
  push:

jobs:

  test_omero:
    runs-on: ubuntu-latest
    name: Test OMERO Helm charts
    steps:
      - uses: actions/checkout@v2
      - id: k3s
        uses: manics/action-k3s-helm@v0.2
        with:
          k3s-version: v1.19.3+k3s1
          helm-version: v3.3.4
          docker-enabled: true
        # This action should export KUBECONFIG
      - name: Install dependencies
        run: |
          conda install -y -q -c ome omero-py pytest
          $CONDA/bin/pip install -r dev-requirements.txt
          echo "$CONDA/bin" >> $GITHUB_PATH
      - name: Build
        run: ./ci/build.sh
      - name: Test
        run: ./ci/test.sh

# TODO: publish

# action "Docker login" {
#   uses = "actions/docker/login@8cdf801b322af5f369e00d85e9cf3a7122f49108"
#   needs = ["Wait for Travis"]
#   secrets = ["DOCKER_USERNAME", "DOCKER_PASSWORD"]
# }

# action "Chartpress" {
#   uses = "manics/chartpress@0.3.1-ghaction.0"
#   needs = ["Docker login"]
#   args = "--git-release --tag-latest --push --publish-chart --git-push"
#   secrets = ["GITHUB_TOKEN"]
# }
